FROM ghcr.io/jenkinsci/jenkinsfile-runner:jre-11@sha256:72ff68c1c368220eb4953a562de3f545404fb5b8c529157b9d6915b90b2c750e
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN cd /app/jenkins && unzip jenkins.war
RUN java -jar /app/bin/jenkins-plugin-manager.jar \
    --war /app/jenkins/jenkins.war \
    --plugin-file /usr/share/jenkins/ref/plugins.txt \
    && rm /app/jenkins/jenkins.war