version: '3'

services:
  recorder:
    image: var_image
    ports:
      - "15901:5901"
    env_file: .env #VNC_PASSWD=...
    volumes:
      # Mounting /root will make all config go away! (OBS, Firefox plugins etc.)
      - ./recorder:/usr/obs
      - ./files:/files:ro
