---
- name: Set up docker-compose machine
  hosts: "{{ target_ip }}"
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker
          - docker-compose

    - name: Creates directory
      file:
        state: directory
        path: /src/app

    - name: Copy files after local_prepate.sh
      ansible.builtin.copy:
        src: "./{{item.src}}"
        dest: "/src/app/{{item.dest}}"
        follow: no # follow links
      loop:
        - src: .remote.env
          dest: .env
        - src: docker-compose.yml
          dest: docker-compose.yml

    - name: Find all files
      ansible.builtin.find:
        paths: /src/app
        recurse: yes
        age: 2d
      register: output

    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: /src/app
        build: false
      register: output
