---
- name: Set up docker-compose machine
  hosts: "{{ target_ip }}"
  remote_user: root
  gather_facts: false # Only after we wait for connection, "setup" bellow
  tasks:
    - name: Wait for VM to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 600 #10min
        delay: 30 #wait before checking
        sleep: 5 #sleep between checks

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Install packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker
          - docker-compose

    - name: Creates directory
      file:
        state: directory
        path: /src/app

    - name: Copy files after local_prepate.sh
      ansible.builtin.copy:
        src: "./{{item.src}}"
        dest: "/src/app/{{item.dest}}"
        follow: no # follow links
      loop:
        - src: .remote.env
          dest: .env
        - src: docker-compose.yml
          dest: docker-compose.yml

    - name: Find all files
      ansible.builtin.find:
        paths: /src/app
        recurse: yes
        age: 2d
      register: output

    - name: Run `docker-compose up`
      docker_compose:
        project_src: /src/app
        build: false
      register: output
